name: CI
on:
  push:
    branches: [develop]

env:
  NOMBRE_DEL_REPO: mi_primer_repo_con_actions
  

jobs:
  build:
    name: Build to Matrix
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, windons-latest,macos-latest]
        node-version: [18,21 ,20]

    steps:
      - name: Clone repo workspace actions
        uses: actions/checkout@v7

      - name: download actions java
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: temurin
      - name: MOSTRANDO Variable DENTRO DEL yml    
        run: echo ${{env.NOMBRE_DEL_REPO}}
      - name: CREANDO variable en ejecucion  
        run: |
            REPO=${{env.NOMBRE_DEL_REPO}}-DEV
            echo $REPO
      - name: Mostrando variable tomado desde github
        run: |
          echo ${{vars.MI_REPO}}
          echo ${{secrets.MI_SECRET}}
  anidado:
    name: prueba de needs
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo workspace actions
        uses: actions/checkout@v7

      - name: download actions java
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: temurin
      - name: MOSTRANDO versuion de java
        run: java -version
       
    
        




    
