name: CI-DEV-JAVA
on:
  push:
    branches: 
      - feature

  pull_request:
    branches:
      - feature
    
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo workspace actions
        uses: actions/checkout@v7

      - name: download actions java
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: temurin
          cache: 'maven'

      - name: Compilar Java
        run: mvn -B clean compile

      - name: compartir compilacion
        uses: actions/upload-artifact@v7
        with:
          name: compilacion-de-clases
          path: target/
          retention-days: 1

  test:
    name: Pruebas unitarias
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo workspace actions
        uses: actions/checkout@v7
        
      - name: download actions java
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: temurin
          cache: 'maven'

      - name: Restaurar binario compilado en build
        uses: actions/download-artifact@v7
        with:
          name: compilacion-de-clases
          path: target/
      - name: Ejecutar pruebas unitarias
        run: mvn -B test
      
      - name: Guardar resultados de pruebas unitarias
        uses: actions/upload-artifact@v7
        with:
          name: resultados-pruebas-unitarias
          path: target/
          retention-days: 1
  
  package:
    name: Empaquetar codigo
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo workspace actions
        uses: actions/checkout@v7
      - name: download actions java
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: temurin
      - name: Restaurar-test-and-dependencias
        uses: actions/download-artifact@v7
        with:
          name: resultados-pruebas-unitarias
          path: target/
      - name: Empaquetar codigo
        run: mvn -B package -DskipTests
      - name: compartir compilacion y empaquetado
        uses: actions/upload-artifact@v7
        with:
          name: package-generate-artifact
          path: target/
          retention-days: 1
  
  public-nexus:
    name: Publicar en Nexus
    needs: package
    runs-on: [self-hosted, nexus]
    steps:
      - name: Clone repo workspace actions
        uses: actions/checkout@v7

      - name: download actions java
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: temurin
          
      - name: Restaurar binario compilado en build
        uses: actions/download-artifact@v7
        with:
          name: package-generate-artifact
          path: target/
      - name: Extraer Parametros de Jar
        id: extraer_parametros
        run: |
          GROUP_ID=$(mvn -q -B help:evaluate -Dexpression=project.groupId -q -DforceStdout)
          ARTIFACT_ID=$(mvn -q -B help:evaluate -Dexpression=project.artifactId -q -DforceStdout)
          VERSION=$(mvn -q -B help:evaluate -Dexpression=project.version -q -DforceStdout)

          echo "group_id=$GROUP_ID" >> $GITHUB_OUTPUT
          echo "artifact_id=$ARTIFACT_ID" >> $GITHUB_OUTPUT
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Determinando carpeta de destino en Nexus
        id: determinar_destino
        env:
          NEXUS_RELEASES_URL: ${{ vars.NEXUS_RELEASES_URL }}
          NEXUS_SNAPSHOTS_URL: ${{ vars.NEXUS_SNAPSHOTS_URL }}
        run: |
          if [[ ${{ steps.extraer_parametros.outputs.version }} == *-SNAPSHOT ]]; then
            echo "destino=$NEXUS_SNAPSHOTS_URL" >> $GITHUB_OUTPUT
          else
            echo "destino=$NEXUS_RELEASES_URL" >> $GITHUB_OUTPUT
          fi

      - name: Publicar en Nexus
        run: |
          JAR_FILE=$(find target -maxdepth 1 -name "*.jar" ! -name "*sources*" ! -name "*javadoc*" | head -n 1)
          curl -Sf -u ${{ secrets.NEXUS_USERNAME }}:${{ secrets.NEXUS_PASSWORD }} \
            -F "maven2.groupId=${{ steps.extraer_parametros.outputs.group_id }}" \
            -F "maven2.artifactId=${{ steps.extraer_parametros.outputs.artifact_id }}" \
            -F "maven2.version=${{ steps.extraer_parametros.outputs.version }}" \
            -F "maven2.asset1=@${JAR_FILE}" \
            -F "maven2.asset1.extension=jar" \
            "${{ vars.NEXUS_URL }}/service/rest/v1/components?repository=${{ steps.determinar_destino.outputs.destino }}"
               



